### PR TITLE
Update Lidarr to 1.2.6.3313 stable.

### PR DESCRIPTION
**Pull request by CompPhy**
This updates the Lidarr chart to use the stable branch, instead of development.  It also updates to the new stable release that came out last week:  1.2.6.3313

### CODE REVIEW

**Comment by CompPhy** [comment]
I would like to link this with https://github.com/truenas/charts/issues/1094 but I'm not sure how to do that.  Please advise, as this is my first time contributing to the community charts.

**Review by stavros-k — CHANGES_REQUESTED** [review]
Change should be done in library/ix-dev/community/lidarr
And the Chart.yaml version bumped by 0.0.1

But in this case I would like to let the CI do the update (in order to verify that the fix here https://github.com/truenas/charts/pull/1350 is working) or if we have to adjust the parsing.
This will ensure future updates will work automatically.

Thanks

**Comment by CompPhy** [comment]
I'm unclear for your response... Do you want me to update things under library/ or are we waiting for your other commit to run some automation?  If the later, is there a place where I can view the status of said automation?

Is there documentation somewhere on the automation parts and how to make proper updates there?  Most of the documentation for contributing talks about the charts folder, so I thought that was the right place to make the change.  If IX really is committed to make this more robust for community contributors, maybe more documentation on how to use the automation is in order??

**Comment by stavros-k** [comment]
> I'm unclear for your response... Do you want me to update things under library/ or are we waiting for your other commit to run some automation? If the later, is there a place where I can view the status of said automation?

First part of the comment was mostly informational, eg for future reference.

The automations is within the `.github/workflows` directory. 
And source code of the scripts running there are in the repositories `truenas/catalog_validation` and `truenas/catalog_update`

> Is there documentation somewhere on the automation parts and how to make proper updates there? Most of the documentation for contributing talks about the charts folder, so I thought that was the right place to make the change. If IX really is committed to make this more robust for community contributors, maybe more documentation on how to use the automation is in order??

Depending on the part of the automation you want to change.
There are some info in the above mentioned repos (truenas/catalog_validation and truenas/catalog_update).
The rest of the automation is plain github actions yaml syntax.

But keep in mind that depending on the change you want to make, knowledge about helm and kubernetes might be needed.


I'm going to close this PR now, as the CI have picked up the newer versions (#1353)
Thanks for taking the time to make this PR

**Pull request closed without merging**
