### PR TITLE
add groups for gpu automatically

### PR DESCRIPTION
**Pull request by stavros-k**
Fixes https://github.com/truenas/charts/issues/2247

### CODE REVIEW

**Review by Qubad786 — APPROVED** [review]

**Comment by wongsyrone** [comment]
@stavros-k 

This is INCORRECT. It should be like below

```
      containers:
        emby:
          enabled: true
          primary: true
          imageSelector: image
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
          fixedEnv:
            PUID: {{ .Values.embyID.user }}
          {{ if .Values.embyGPU }}
          env:
            GIDLIST: 44,107
          {{ end }}
          {{ with .Values.embyConfig.additionalEnvs }}
          envList:
            {{ range $env := . }}
            - name: {{ $env.name }}
              value: {{ $env.value }}
            {{ end }}
          {{ end }}
```

**Comment by stavros-k** [comment]
> @stavros-k 
> 
> 
> 
> This is INCORRECT. It should be like below
> 
> 
> 
> ```
> 
>       containers:
> 
>         emby:
> 
>           enabled: true
> 
>           primary: true
> 
>           imageSelector: image
> 
>           securityContext:
> 
>             runAsUser: 0
> 
>             runAsGroup: 0
> 
>             runAsNonRoot: false
> 
>             readOnlyRootFilesystem: false
> 
>             capabilities:
> 
>               add:
> 
>                 - CHOWN
> 
>                 - DAC_OVERRIDE
> 
>                 - FOWNER
> 
>                 - SETGID
> 
>                 - SETUID
> 
>           fixedEnv:
> 
>             PUID: {{ .Values.embyID.user }}
> 
>           {{ if .Values.embyGPU }}
> 
>           env:
> 
>             GIDLIST: 44,107
> 
>           {{ end }}
> 
>           {{ with .Values.embyConfig.additionalEnvs }}
> 
>           envList:
> 
>             {{ range $env := . }}
> 
>             - name: {{ $env.name }}
> 
>               value: {{ $env.value }}
> 
>             {{ end }}
> 
>           {{ end }}
> 
> ```

Can you clarify why is that incorrect?
Did you shell in the container and the env was not set?

**Comment by wongsyrone** [comment]
I upgraded to that version and the env doesn't take effect. I moved them out of `additionalEnvs`, everything works.

**Comment by stavros-k** [comment]
Okay I now that I had enough coffee, I see what you said. You are correct. Fixing in a bit.

Thanks for pointing out.

**Comment by wongsyrone** [comment]
To clarify, I don't have any graphical cards, only iGPU from Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

**Comment by stavros-k** [comment]
> To clarify, I don't have any graphical cards, only iGPU from Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

As long as any GPU is selected in the dropdown it should work (after #2258)

**Comment by wongsyrone** [comment]
Good job. Thanks for the quick response.

**Pull request merged**
