### PR TITLE
NAS-119497 / 23.10 / storj-update-stable

### PR DESCRIPTION
**Pull request by stavros-k**
As mentioned in #926, `v1.66.4` was a pre-release version.

Updating to a stable version

### CODE REVIEW

**Review by Qubad786 — APPROVED** [review]
Why didn't upgrade strategy work 🤔?

**Comment by stavros-k** [comment]
> Why didn't upgrade strategy work thinking?

Their releases don't follow a scheme that can differentiate pre-releases from releases, for that reason we disabled the update strategy

**Comment by Qubad786** [comment]
@stavros-k let's re-enable it then?

**Comment by stavros-k** [comment]
> @stavros-k let's re-enable it then?

It's still the case. If we re-enable them we will just get daily prompts from the bot to update to a pre-release

**Pull request merged**
