### PR TITLE
NAS-119496 / 23.10 / fix nextcloud secret and update

### PR DESCRIPTION
**Pull request by stavros-k**
Fixed: 
- Secret on nextcloud for `db-details` which was missing the `b64enc` on `db-user`
- Made the random generation of password more robust.
- Postgres Database name defaults to postgres user, while the username (as `nextcloud`) was used in all nextcloud references. the postgres user was set to `postgres`. So postgres was creating a `postgres` database but nextcloud was trying to connect to `nextcloud` database.

Updated:
- nextcloud container
- nginx container

Note: All values under `data` in secrets must be `base64` encrypted.

### CODE REVIEW

**Review by Qubad786 — COMMENTED** [review]
@stavros-k do upgrades to this newer version break older setups?

**Comment by stavros-k** [comment]
> @stavros-k do upgrades to this newer version break older setups?

Correct observation...

I'm confused as to how it worked currently.
This is the env value for the current postgres, also check the postgres password

image

And this is how nextcloud config looks like
image

So yea, it's defintely breaking older setups. Which means we also need to change major version number at least.

**Comment by Ornias1993** [comment]
Though the underlaying problem is the fact that nothing is actually install-tested at the moment.
I would suggest waiting for the new common and merging this + the new common + actuall tests all-at-once.

**Comment by Ornias1993** [comment]
Last change could work @stavros-k :)

**Comment by stavros-k** [comment]
Did the following test after my last change:

- Created a new branch.
- Copied `.14` NC chart 
- Pasted to `.15`
- Applied changes to `.15`
- Removed catalog.json
- Added repo/branch to Scale
- Installed .14
- Logged in the UI created files/user/etc
- Upgraded to .15
- Everything worked fine.
- Also checked env variables and stayed all the same

**Review by Ornias1993 — APPROVED** [review]
While far from perfect, this at least solves the issue for now. 
LGTM 👍

**Review by Qubad786 — APPROVED** [review]
LGTM 👍

**Pull request merged**
