### PR TITLE
Small naming improvement

### PR DESCRIPTION
**Pull request by aidik**
We would like to use this information on the public-facing website so I added few small naming improvements.

### CODE REVIEW

**Review by sonicaj — APPROVED** [review]

**Comment by sonicaj** [comment]
@aidik can you please resolve the conflicts and update the PR ? Thanks

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
- The App readme's are inconsistent (1 uses `#` and 2 use `====`)
- It's not sure why this is needed, as the App readme in UI is displayed with a title already, the lack of UI screenshots in the PR description makes it hard to evaluate this PR.

**Comment by sonicaj** [comment]
ping @aidik

**Comment by sonicaj** [comment]
Closing this PR as it's been a few months now.

**Pull request closed without merging**
