### PR TITLE
NAS-114444 / 22.02 / Add Shibgreen support for Machinaris

### PR DESCRIPTION
**Pull request by Sagittarius**
Add Shibgreen support and optimize environment variable: "`controller_host`", "`controller_api_port`"

### CODE REVIEW

**Review by Qubad786 — CHANGES_REQUESTED** [review]
Thanks for submitting the PR @Sagittarius :)

Can you please:
1. Bump the machinaris version to 1.1.2
2. Update the `test` train with these changes and bump version there too

**Comment by Sagittarius** [comment]
> Thanks for submitting the PR @Sagittarius :)
> 
> Can you please:
> 
> 1. Bump the machinaris version to 1.1.2
> 2. Update the `test` train with these changes and bump version there too

Can you tell me witch `test` train? Do you mean `test` branche?

**Comment by Qubad786** [comment]
@Sagittarius we have two trains: `charts` and `test`, you have made updates to `charts` train we need those similar updates into `test` train as well: https://github.com/truenas/charts/tree/master/test/machinaris

Why do we have two trains?
We normally develop in test train and when we're confident that an app is working as expected we move it to `charts` train.

**Comment by Qubad786** [comment]
Also, feel free to on-board MMX as well if you like ;) (from [machinaris.app](https://www.machinaris.app/)):
```yaml
machinaris-mmx: 
        image: ghcr.io/guydavis/machinaris-mmx:develop 
        container_name: machinaris-mmx 
        hostname: 192.168.0.1 
        restart: always 
        volumes: 
            - ~/.machinaris-mmx:/root/.chia 
            - "/mnt/disk1/mmx:/plots1" 
            - "/mnt/tmp1:/plotting" 
        environment: 
            - TZ=Asia/Karachi 
            - mode=fullnode 
            - controller_host=192.168.0.1 
            - worker_address=192.168.0.1 
            - worker_api_port=8940 
            - plots_dir=/plots1 
            - blockchains=mmx 
        ports: 
            - 8940:8940 
            - 12333:12333 
            - 11330:11330 
        depends_on: 
            - machinaris 
```

**Comment by Sagittarius** [comment]
MMX is only support by `:develop` tag image. Is it a good idea to add  it to release train?

**Comment by Qubad786** [comment]
@Sagittarius I see, let's ignore me on that :)

**Comment by Sagittarius** [comment]
Bump to version 1.1.2 now, and also test train

**Review by Qubad786 — APPROVED** [review]
LGTM! @Sagittarius thanks for taking to finishing line! 🎉

**Pull request merged**
