### PR TITLE
NAS-115858 / 22.12 / Fix netdata hitting apparmor profile

### PR DESCRIPTION
**Pull request by miguelangel-nubla**
Netdata hitting apparmor is spamming logs:
```
Apr 19 21:52:04 truenas kernel: audit: type=1400 audit(1650397924.087:7477502): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2185738 comm="apps.plugin" requested_mask="read" denied_mask="read" peer="unconfined"
```

[Official netdata chart](https://github.com/netdata/helmchart/blob/master/charts/netdata/templates/daemonset.yaml) uses unconfined apparmor declaration.

### CODE REVIEW

**Review by Qubad786 — COMMENTED** [review]
@miguelangel-nubla your contribution is much appreciated!
Can you make the following changes as well:
1. Update `test` train and bump the app version to `1.0.4` and update `Chart.yaml` accordingly to reflect the newer version
2. Bump the app version in `charts` train and corresponding `Chart.yaml` change as well

**Comment by Ornias1993** [comment]
I wonder, in our experience SCALE does not actually use AppArmour, or is this a nightly things @Qubad786 ?

**Comment by Ornias1993** [comment]
@Qubad786 We've also added netdata and also have no issues like this... Afaik apparmour is also not enabled, so I do not see the need for this.

**Comment by sonicaj** [comment]
ping @Qubad786

**Comment by Qubad786** [comment]
@miguelangel-nubla can you email me a debug of your system when you see this issue at mrehan@ixsystems.com please so we can investigate/see the exact configuration case which is causing this?

I was not able to reproduce this either..

**Comment by miguelangel-nubla** [comment]
I updated my system, currently in TrueNAS-SCALE-22.02.2.1 and can no longer reproduce the issue.
I originally reported it while running SCALE-22.12-BETA.1, so must have been fixed along the way.

**Comment by Ornias1993** [comment]
> I originally reported it while running SCALE-22.12-BETA.1, so must have been fixed along the way.

I think you're mistaken there. As that version does not even exist, because 22.12 isn't technically even in ALPHA.1 yet.

**Pull request closed without merging**
