### PR TITLE
Add metadata to allow automated updates of catalog item(s)

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]
From my limited understanding, this looks 👍🏼 ... but I'd feel a warm fuzzy if I had @yocalebo's eyes on it as well.

**Review by yocalebo — APPROVED** [review]

**Comment by rick-mesta** [comment]
Thx for the ⚡ fast review, @yocalebo 🥰

**Comment by Ornias1993** [comment]
Just to be clear: This looks to be updates of catalog item Image Tag, not the actual catalog items themselves, right?
Aka: It updates the tags, but does not automatically update the catalog item when newer versions of the catalog item are available, right?

**Comment by sonicaj** [comment]
@Ornias1993 this basically helps automate pushing newer versions of catalog item(s) when a newer image tag is available for a catalog item. `catalog_update` can be used which uses these metadata files and then makes a PR with the newer catalog item(s) using newer image tags ( if available ).

**Pull request merged**
