### PR TITLE
Update Tdarr to 2.20.01

### PR DESCRIPTION
**Pull request by Urkaz**
2.20.01 is currently the last version available.

https://github.com/haveagitgat/Tdarr/pkgs/container/tdarr
https://hub.docker.com/r/haveagitgat/tdarr/tags

Thanks :)

### CODE REVIEW

**Comment by stavros-k** [comment]
Hello, please see #2583

**Comment by Urkaz** [comment]
Oh, I didn't see that.
That will allow automatic updates so there is no need for this PR?

**Comment by stavros-k** [comment]
> Oh, I didn't see that. That will allow automatic updates so there is no need for this PR?

Yes that's correct!

**Comment by swensorm** [comment]
Hmm... Did I miss something though?  2.21.01 was also released today but I don't see a PR getting created that includes either update 😕

**Comment by swensorm** [comment]
Oh, shoot, I see the issue.  Tdarr wonderfully versions things as "2.21.01" but the parsed version is "2.21.1".  On line 22 it tries to index the `tags` array with "2.21.1" which doesn't exist.

Suggestions on how to fix? 🤔

**Comment by Urkaz** [comment]
Ok, I'll close this then.
Thank you both for your work, stavros-k and swensorm! :)

**Comment by swensorm** [comment]
Woohoo!  Looks to have worked 🎉

https://github.com/truenas/charts/pull/2616

**Pull request closed without merging**
